In [1]:
import pandas as pd

In [5]:
pd.set_option("display.max_rows",None,"display.max_columns",None)

In [6]:
bond=pd.read_csv("jamesbond.csv")

In [7]:
bond

,Year,Movie,Bond,Director,Composer,Writer,Cinematographer,Depicted_Film_Loc,Shooting_Loc,Bond_Car_MFG,Bond_Girl_Nat,US_Gross,US_Adj,World_Gross,World_Adj,Budget,Budget_Adj,Film_Length,Avg_User_IMDB,Avg_User_Rtn_Tom,Conquests,Martinis,BJB,Kills_Bond,Kills_Others,Top_100,Video_Game
0,1962,Dr. No,Sean Connery,Terence Young,Monty Norman,"Richard Maibaum, Johanna Harwood & Berkely Mather",Ted Moore,"Great Britain, Jamaic","England, Jamaica",Sunbeam,"Swiss, English, English",16067035,123517,59567035,457928,1000,7688,110,7.3,7.7,3,2,1,4,8,0,0
1,1963,From Russia with Love,Sean Connery,Terence Young,John Barry,Richard Maibaum & Johanna Harwood,Ted Moore,"United Kingdom, Great Britain, Turkey, Croatia...","England, Scotland, Italy, Switzerland, Turkey",Bently,"English, Italian, English, Israeli",24800000,188161,78900000,598624,2000,15174,115,7.5,8.0,4,0,0,11,16,0,1
2,1964,Goldfinger,Sean Connery,Guy Hamilton,John Barry,Richard Maibaum & Paul Dehn,Ted Moore,"United States, Great Britain, Switzerland","England, Switzerland, United States",Aston Martin,"Serbian, English",51100000,382699,124900000,935404,3000,22468,110,7.8,8.4,2,1,2,9,68,1,1
3,1965,Thunderball,Sean Connery,Terence Young,John Barry,Richard Maibaum & John Hopkins,Ted Moore,"France, Great Britain, Bahamas, United States","England, France, Bahamas, United States",Aston Martin,"French, Italian, Bahamian",63600000,468754,141200000,1040693,9000,66333,130,7.0,6.8,3,0,0,20,90,1,0
4,1967,You Only Live Twice,Sean Connery,Lewis Gilbert,John Barry,Roald Dahl,Freddie Young,"United States, Russia, Kazakhstan, Norway, Japan","Japan, Spain, Norway",Toyota,"Japanese, Chinese, German",43100000,299591,111600000,775740,9500,66035,117,6.9,6.3,3,1,0,21,175,1,0
5,1969,On Her Majesty's Secret Service,George Lazenby,Peter R. Hunt,John Barry,Richard Maibaum,Michael Reed,"Portugal, Great Britain, Switzerland","England, Switzerland, Portugal",Mercury,"English, English, Hungarian",22800000,144234,82000000,518736,8000,50608,142,6.8,6.7,3,1,2,5,37,0,0
6,1971,Diamonds Are Forever,Sean Connery,Guy Hamilton,John Barry,Richard Maibaum & Tom Mankiewicz,Ted Moore,"Japan, Egypt, France, South Africa, Great Brit...","England, France, Germany, Netherlands, United ...",Ford,American,43800000,251083,116000000,664969,7200,41274,120,6.7,6.3,1,0,1,7,42,1,0
7,1973,Live and Let Die,Roger Moore,Guy Hamilton,George Martin,Tom Mankiewicz,Ted Moore,"United States, Great Britain, Jamaica","England, United States, Jamaica",AMC,"English, American, English",35400000,185105,161800000,846046,7000,36603,121,6.8,5.9,3,0,1,8,5,1,1
8,1974,The Man with the Golden Gun,Roger Moore,Guy Hamilton,John Barry,Richard Maibaum & Tom Mankiewicz,Ted Moore,"Great Britain, Lebanon, Portugal, Thailand","England, Thailand, Hong Kong, Portugal",AMC,"Sweedish, French",21000000,98894,97600000,459623,7000,32965,125,6.7,5.1,2,0,2,1,5,0,0
9,1977,The Spy Who Loved Me,Roger Moore,Lewis Gilbert,Marvin Hamlisch,Christopher Wood & Richard Maibaum,Claude Renoir,"Austria, Russia, Great Britain, Egypt, Italy","England, Switzerland, Canada, Scotland, Egypt,...",Lotus,"American, English, Bosnian",46800000,179297,185400000,710290,14000,53636,125,7.1,6.8,3,1,1,31,116,1,1
10,1979,Moonraker,Roger Moore,Lewis Gilbert,John Barry,Christopher Wood,Jean Tournier,"Great Britain, United States, Italy, Brazil, R...","England, France, Italy, United States, Brazil,...",Lotus,"American, French, Moroccan",70300000,224811,210300000,672514,31000,99134,126,6.2,5.7,3,1,1,12,69,0,0
11,1981,For Your Eyes Only,Roger Moore,John Glen,Bill Conti,Michael G. Wilson & Richard Maibaum,Alan Hume,"Great Britain, Russia, Spain, Italy, Greece, A...","England, Italy, Malta, Greece",Citroën,"French, Australian",54800000,139964,195300000,498812,28000,71514,127,6.8,6.3,2,0,2,18,36,1,0
12,1983,Octopussy,Roger Moore,John Glen,John Barry,"George MacDonald Fraser, Michael G. Wilson & R...",Alan Hume,"Great Britain, India, Russia, Germany","England, West Berlin, India",Bajaj,"Sweedish, English",67900000,158274,187500000,437059,27500,64102,131,6.5,5.3,2,0,1,15,43,1,0
13,1985,A View to a Kill,Roger Moore,John Glen,John Barry,Michael G. Wilson & Richard Maibaum,Alan Hume,"Russia, Great Britain, France, United States","England, Switzerland, Iceland, France, United ...",Rolls Royce,"American, Jamaican, Sweedish, Nigerian",50327960,108592,152627960,329322,30000,64730,131,6.2,4.7,4,0,2,5,57,1,0
14,1987,The Living Daylights,Timothy Dalton,John Glen,John Barry,Michael G. Wilson & Richard Maibaum,Alec Mills,"Gibraltar, Great Britain, Slovakia, Austria, M...","England, Germany, Austria, Italy, Morocco",Rolls Royce,"Dutch, American",51185000,104608,191200000,390758,40000,81749,130,6.7,6.3,2,2,1,13,29,0,0
15,1989,License to Kill,Timothy Dalton,John Glen,Michael Kamen,Michael G. Wilson & Richard Maibaum,Alec Mills,"United States, Bahamas, Great Britain","Mexico, United States",Aston Martin,"American, American",34667015,64907,156167015,292392,42000,78637,133,6.5,6.0,2,1,1,10,13,0,1
16,1995,GoldenEye,Pierce Brosnan,Martin Campbell,Éric Serra,"Michael France, Jeffrey Caine, Kevin Wade & Br...",Phil Méheux,"Russia, Monaco, France, England, United States...","England, France, Monaco, Switzerland, Russia, ...",BMW,"Polish, Dutch",106429941,162135,356429941,542985,60000,91404,130,7.2,6.9,2,1,1,47,25,0,1
17,1997,Tomorrow Never Dies,Pierce Brosnan,Roger Spottiswoode,David Arnold,Bruce Feirstein,Robert Elswit,"Russia, England, Germany, Vietnam","England, France, Germany, Thailand",Aston Martin,"Malaysian, American, Danish",125304276,181254,339504276,491098,110000,159117,119,6.4,6.0,3,1,1,30,24,0,1
18,1999,The World Is Not Enough,Pierce Brosnan,Michael Apted,David Arnold,"Neal Purvis, Robert Wade & Bruce Feirstein",Adrian Biddle,"Spain, England, Scotland, Kazakhstan, Azerbaij...","England, Scotland, France, Spain, Turkey, Azer...",BMW,"American, French, English",126930660,176885,361730660,504091,135000,188130,128,6.3,5.7,3,1,2,27,43,0,1
19,2002,Die Another Day,Pierce Brosnan,Lee Tamahori,David Arnold,Neal Purvis and Robert Wade,David Tattersall,"South Korea, Hong Kong, Cube, England, Iceland","England, Spain, Iceland, Norway, United States",Aston Martin,"American, Filipino",160942139,207700,431942139,557433,142000,183255,133,6.0,6.1,2,2,1,31,20,1,0
20,2006,Casino Royale,Daniel Craig,Martin Campbell,David Arnold,"Neal Purvis, Robert Wade & Paul Haggis",Phil Méheux,"Czech Republic, Pakistan, Uganda, Madagascar, ...","England, Italy, Czech republic, Bahamas, Unite...",Aston Martin,"French, Italian",167365000,192740,596365000,686784,102000,117465,144,7.9,7.8,2,3,1,11,11,1,0
21,2008,Quantum of Solace,Daniel Craig,Marc Forster,David Arnold,Paul Haggis and Neal Purvis and Robert Wade,Roberto Schaefer,"Italy, England, Haiti, Austria, Bolivia, Russia","England, Italy, Spain, Panama, Mexico, Chile, ...",Aston Martin,English,169368427,182633,591692078,638035,230000,248014,106,6.7,6.1,1,6,0,16,15,1,1
22,2012,Skyfall,Daniel Craig,Sam Mendes,Thomas Newman,"Neal Purvis, Robert Wade & John Logan",Roger Deakins,"Turkey, England, China, Macau, Japan, Scotland","England, Scotland, Turkey, China",Aston Martin,"French, Greek, English",304360277,307770,1108561108,1120980,200000,202240,143,7.8,8.2,3,1,1,26,26,1,0
23,2015,Spectre,Daniel Craig,Sam Mendes,Thomas Newman,"John Logan & Neal Purvis, Robert Wade & Jez Bu...",Hoyte van Hoytema,"Mexico, England, Italy, Austria, Morocco, Vati...","England, Austria, Italy, Vatican City, Mexico,...",Aston Martin,"French, Italian, Mexican",200074175,196647,879620923,864553,245000,240803,148,6.8,6.4,3,1,1,30,205,1,0

In [8]:
bond.set_index("Movie",inplace=True)

In [9]:
bond.sort_index(inplace=True)

In [10]:
bond.head()

,Year,Bond,Director,Composer,Writer,Cinematographer,Depicted_Film_Loc,Shooting_Loc,Bond_Car_MFG,Bond_Girl_Nat,US_Gross,US_Adj,World_Gross,World_Adj,Budget,Budget_Adj,Film_Length,Avg_User_IMDB,Avg_User_Rtn_Tom,Conquests,Martinis,BJB,Kills_Bond,Kills_Others,Top_100,Video_Game
Movie,,,,,,,,,,,,,,,,,,,,,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,John Barry,Michael G. Wilson & Richard Maibaum,Alan Hume,"Russia, Great Britain, France, United States","England, Switzerland, Iceland, France, United ...",Rolls Royce,"American, Jamaican, Sweedish, Nigerian",50327960,108592,152627960,329322,30000,64730,131,6.2,4.7,4,0,2,5,57,1,0
Casino Royale,2006,Daniel Craig,Martin Campbell,David Arnold,"Neal Purvis, Robert Wade & Paul Haggis",Phil Méheux,"Czech Republic, Pakistan, Uganda, Madagascar, ...","England, Italy, Czech republic, Bahamas, Unite...",Aston Martin,"French, Italian",167365000,192740,596365000,686784,102000,117465,144,7.9,7.8,2,3,1,11,11,1,0
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,John Barry,Richard Maibaum & Tom Mankiewicz,Ted Moore,"Japan, Egypt, France, South Africa, Great Brit...","England, France, Germany, Netherlands, United ...",Ford,American,43800000,251083,116000000,664969,7200,41274,120,6.7,6.3,1,0,1,7,42,1,0
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,David Arnold,Neal Purvis and Robert Wade,David Tattersall,"South Korea, Hong Kong, Cube, England, Iceland","England, Spain, Iceland, Norway, United States",Aston Martin,"American, Filipino",160942139,207700,431942139,557433,142000,183255,133,6.0,6.1,2,2,1,31,20,1,0
Dr. No,1962,Sean Connery,Terence Young,Monty Norman,"Richard Maibaum, Johanna Harwood & Berkely Mather",Ted Moore,"Great Britain, Jamaic","England, Jamaica",Sunbeam,"Swiss, English, English",16067035,123517,59567035,457928,1000,7688,110,7.3,7.7,3,2,1,4,8,0,0

In [13]:
def convert_to_string_and_add_millions(number):
    return str(number)+"Millions!"

In [15]:
bond["Budget"]=bond["Budget"].apply(convert_to_string_and_add_millions)

In [16]:
columns=["Budget","Budget_Adj","World_Adj"]

In [17]:
for col in columns:
    bond[col]=bond[col].apply(convert_to_string_and_add_millions)

In [19]:
bond.head(2)

,Year,Bond,Director,Composer,Writer,Cinematographer,Depicted_Film_Loc,Shooting_Loc,Bond_Car_MFG,Bond_Girl_Nat,US_Gross,US_Adj,World_Gross,World_Adj,Budget,Budget_Adj,Film_Length,Avg_User_IMDB,Avg_User_Rtn_Tom,Conquests,Martinis,BJB,Kills_Bond,Kills_Others,Top_100,Video_Game
Movie,,,,,,,,,,,,,,,,,,,,,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,John Barry,Michael G. Wilson & Richard Maibaum,Alan Hume,"Russia, Great Britain, France, United States","England, Switzerland, Iceland, France, United ...",Rolls Royce,"American, Jamaican, Sweedish, Nigerian",50327960,108592,152627960,329322Millions!,30000Millions!Millions!,64730Millions!,131,6.2,4.7,4,0,2,5,57,1,0
Casino Royale,2006,Daniel Craig,Martin Campbell,David Arnold,"Neal Purvis, Robert Wade & Paul Haggis",Phil Méheux,"Czech Republic, Pakistan, Uganda, Madagascar, ...","England, Italy, Czech republic, Bahamas, Unite...",Aston Martin,"French, Italian",167365000,192740,596365000,686784Millions!,102000Millions!Millions!,117465Millions!,144,7.9,7.8,2,3,1,11,11,1,0

In [20]:
bond=pd.read_csv("jamesbond.csv",index_col="Movie")

In [21]:
bond.sort_index(inplace=True)
bond.head(2)

,Year,Bond,Director,Composer,Writer,Cinematographer,Depicted_Film_Loc,Shooting_Loc,Bond_Car_MFG,Bond_Girl_Nat,US_Gross,US_Adj,World_Gross,World_Adj,Budget,Budget_Adj,Film_Length,Avg_User_IMDB,Avg_User_Rtn_Tom,Conquests,Martinis,BJB,Kills_Bond,Kills_Others,Top_100,Video_Game
Movie,,,,,,,,,,,,,,,,,,,,,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,John Barry,Michael G. Wilson & Richard Maibaum,Alan Hume,"Russia, Great Britain, France, United States","England, Switzerland, Iceland, France, United ...",Rolls Royce,"American, Jamaican, Sweedish, Nigerian",50327960,108592,152627960,329322,30000,64730,131,6.2,4.7,4,0,2,5,57,1,0
Casino Royale,2006,Daniel Craig,Martin Campbell,David Arnold,"Neal Purvis, Robert Wade & Paul Haggis",Phil Méheux,"Czech Republic, Pakistan, Uganda, Madagascar, ...","England, Italy, Czech republic, Bahamas, Unite...",Aston Martin,"French, Italian",167365000,192740,596365000,686784,102000,117465,144,7.9,7.8,2,3,1,11,11,1,0

In [27]:
 def good_movie(row):
    director=row[2]
    budget=row[14]
    if director=="John Glen":
        return "the best"
    elif director=="Martin Campbell" and budget>30000:
        return "enjoyable"
    else:
        return "i have no clue"

In [28]:
bond.apply(good_movie,axis="columns")

Movie
A View to a Kill                         the best
Casino Royale                           enjoyable
Diamonds Are Forever               i have no clue
Die Another Day                    i have no clue
Dr. No                             i have no clue
For Your Eyes Only                       the best
From Russia with Love              i have no clue
GoldenEye                               enjoyable
Goldfinger                         i have no clue
License to Kill                          the best
Live and Let Die                   i have no clue
Moonraker                          i have no clue
Octopussy                                the best
On Her Majesty's Secret Service    i have no clue
Quantum of Solace                  i have no clue
Skyfall                            i have no clue
Spectre                            i have no clue
The Living Daylights                     the best
The Man with the Golden Gun        i have no clue
The Spy Who Loved Me               i have no clue
The World Is Not Enough            i have no clue
Thunderball                        i have no clue
Tomorrow Never Dies                i have no clue
You Only Live Twice                i have no clue
dtype: object

In [29]:
def good_movie(row):
    director=row[2]
    budget=row[14]
    if director=="John Glen":
        return "the best"
    elif director=="Martin Campbell" and budget > 30000:
        return "enjoyable"
    else:
        return "i have no clue"

In [31]:
bond.apply(good_movie,axis="columns")

Movie
A View to a Kill                         the best
Casino Royale                           enjoyable
Diamonds Are Forever               i have no clue
Die Another Day                    i have no clue
Dr. No                             i have no clue
For Your Eyes Only                       the best
From Russia with Love              i have no clue
GoldenEye                               enjoyable
Goldfinger                         i have no clue
License to Kill                          the best
Live and Let Die                   i have no clue
Moonraker                          i have no clue
Octopussy                                the best
On Her Majesty's Secret Service    i have no clue
Quantum of Solace                  i have no clue
Skyfall                            i have no clue
Spectre                            i have no clue
The Living Daylights                     the best
The Man with the Golden Gun        i have no clue
The Spy Who Loved Me               i have no clue
The World Is Not Enough            i have no clue
Thunderball                        i have no clue
Tomorrow Never Dies                i have no clue
You Only Live Twice                i have no clue
dtype: object